#!/usr/bin/env bash

FZF_OPTS=(
--cycle
--reverse
--border
--prompt=Search:
--bind shift-up:preview-page-up
--bind shift-down:preview-page-down
--bind ctrl-c:abort
--bind ctrl-q:abort
--bind esc:abort
)

pacman -Qeq | fzf "${FZF_OPTS[@]}" --ansi --preview-window=bottom,75% --preview="pacman -Qi {}"

#packman -Qeq --explicitly installed
#pacman -Qd --dependent packages