#!/usr/bin/env bash

CONFIG_FILES="$HOME/.config/sway/waybar/config $HOME/.config/sway/waybar/style.css"

trap "killall waybar" EXIT

while true; do
    waybar --config "$HOME/.config/sway/waybar/config" --style "$HOME/.config/sway/waybar/style.css" &
    inotifywait -e create,modify $CONFIG_FILES
    killall waybar
done

